// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for crew documents */
interface CrewDocumentData {
    /**
     * name field in *crew*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: crew.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * about field in *crew*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: crew.about
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about: prismicT.RichTextField;
    /**
     * image field in *crew*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: crew.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * crew document from Prismic
 *
 * - **API ID**: `crew`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CrewDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<CrewDocumentData>, "crew", Lang>;
/** Content for footer documents */
interface FooterDocumentData {
    /**
     * links field in *footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.links[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    links: prismicT.GroupField<Simplify<FooterDocumentDataLinksItem>>;
}
/**
 * Item in footer → links
 *
 */
export interface FooterDocumentDataLinksItem {
    /**
     * link field in *footer → links*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.links[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * label field in *footer → links*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.links[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
}
/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for global settings documents */
interface GlobalSettingsDocumentData {
    /**
     * main menu field in *global settings*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.main_menu[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    main_menu: prismicT.GroupField<Simplify<GlobalSettingsDocumentDataMainMenuItem>>;
    /**
     * page title field in *global settings*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.page_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * page description field in *global settings*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.page_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_description: prismicT.KeyTextField;
    /**
     * logo field in *global settings*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * front left image field in *global settings*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.front_left_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    front_left_image: prismicT.ImageField<never>;
    /**
     * front right image field in *global settings*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.front_right_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    front_right_image: prismicT.ImageField<never>;
    /**
     * link share image field in *global settings*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.link_share_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    link_share_image: prismicT.ImageField<never>;
    /**
     * email field in *global settings*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.email
     * - **Tab**: contact information
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    email: prismicT.LinkField;
    /**
     * social media field in *global settings*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.social_media[]
     * - **Tab**: contact information
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social_media: prismicT.GroupField<Simplify<GlobalSettingsDocumentDataSocialMediaItem>>;
}
/**
 * Item in global settings → main menu
 *
 */
export interface GlobalSettingsDocumentDataMainMenuItem {
    /**
     * menu field in *global settings → main menu*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.main_menu[].menu
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu: prismicT.RelationField<"new_menu">;
}
/**
 * Item in global settings → social media
 *
 */
export interface GlobalSettingsDocumentDataSocialMediaItem {
    /**
     * platform field in *global settings → social media*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.social_media[].platform
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    platform: prismicT.SelectField<"facebook" | "instagram">;
    /**
     * link field in *global settings → social media*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: global_settings.social_media[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * global settings document from Prismic
 *
 * - **API ID**: `global_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalSettingsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<GlobalSettingsDocumentData>, "global_settings", Lang>;
/** Content for homepage documents */
interface HomepageDocumentData {
    /**
     * name field in *homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * image field in *homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * video field in *homepage*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.video
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    video: prismicT.LinkToMediaField;
    /**
     * video backup field in *homepage*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.video_backup
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    video_backup: prismicT.LinkToMediaField;
    /**
     * Slice Zone field in *homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
    /**
     * page title field in *homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.page_title
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * page description field in *homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.page_description
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_description: prismicT.KeyTextField;
    /**
     * page image field in *homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.page_image
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    page_image: prismicT.ImageField<never>;
}
/**
 * Slice for *homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = PageHeadSectionSlice | SoundsSlice | ImagesSlice;
/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for menu documents */
interface MenuDocumentData {
    /**
     * items field in *menu*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    items: prismicT.GroupField<Simplify<MenuDocumentDataItemsItem>>;
    /**
     * Slice Zone field in *menu*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<MenuDocumentDataSlicesSlice>;
}
/**
 * Item in menu → items
 *
 */
export interface MenuDocumentDataItemsItem {
    /**
     * svg field in *menu → items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].svg
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    svg: prismicT.ImageField<never>;
    /**
     * link field in *menu → items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * link id field in *menu → items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].link_id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_id: prismicT.KeyTextField;
    /**
     * postfix field in *menu → items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].postfix
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    postfix: prismicT.KeyTextField;
}
/**
 * Slice for *menu → Slice Zone*
 *
 */
type MenuDocumentDataSlicesSlice = never;
/**
 * menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
/** Content for new menu documents */
interface NewMenuDocumentData {
    /**
     * label field in *new menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: new_menu.label
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * svg title field in *new menu*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: new_menu.svg_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    svg_title: prismicT.ImageField<never>;
    /**
     * image field in *new menu*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: new_menu.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * submenu field in *new menu*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: new_menu.submenu[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    submenu: prismicT.GroupField<Simplify<NewMenuDocumentDataSubmenuItem>>;
}
/**
 * Item in new menu → submenu
 *
 */
export interface NewMenuDocumentDataSubmenuItem {
    /**
     * label field in *new menu → submenu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: new_menu.submenu[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * link field in *new menu → submenu*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: new_menu.submenu[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * new menu document from Prismic
 *
 * - **API ID**: `new_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewMenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NewMenuDocumentData>, "new_menu", Lang>;
/** Content for page documents */
interface PageDocumentData {
    /**
     * title field in *page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * background field in *page*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: page.background
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background: prismicT.ColorField;
    /**
     * Slice Zone field in *page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
    /**
     * page title field in *page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_title
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * page description field in *page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_description
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_description: prismicT.KeyTextField;
    /**
     * page image field in *page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_image
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    page_image: prismicT.ImageField<never>;
}
/**
 * Slice for *page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = PageHeadSectionSlice | SoundsSlice | CrewSectionSliceSlice | ImagesSlice | ProjectListSliceSlice;
/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for project documents */
interface ProjectDocumentData {
    /**
     * title field in *project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * subtitle field in *project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.subtitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * background field in *project*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: project.background
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background: prismicT.ColorField;
    /**
     * Slice Zone field in *project*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ProjectDocumentDataSlicesSlice>;
    /**
     * page title field in *project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.page_title
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * page description field in *project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.page_description
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_description: prismicT.KeyTextField;
    /**
     * page image field in *project*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.page_image
     * - **Tab**: seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    page_image: prismicT.ImageField<never>;
}
/**
 * Slice for *project → Slice Zone*
 *
 */
type ProjectDocumentDataSlicesSlice = TextAndBoxesSlice | PageHeadSectionSlice;
/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;
/** Content for sound documents */
interface SoundDocumentData {
    /**
     * title field in *sound*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sound.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * file field in *sound*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: sound.file
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    file: prismicT.LinkToMediaField;
}
/**
 * sound document from Prismic
 *
 * - **API ID**: `sound`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SoundDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SoundDocumentData>, "sound", Lang>;
export type AllDocumentTypes = CrewDocument | FooterDocument | GlobalSettingsDocument | HomepageDocument | MenuDocument | NewMenuDocument | PageDocument | ProjectDocument | SoundDocument;
/**
 * Primary content in CrewSectionSlice → Primary
 *
 */
interface CrewSectionSliceSliceDefaultPrimary {
    /**
     * svg title field in *CrewSectionSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: crew_section_slice.primary.svg_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    svg_title: prismicT.ImageField<never>;
}
/**
 * Item in CrewSectionSlice → Items
 *
 */
export interface CrewSectionSliceSliceDefaultItem {
    /**
     * crew field in *CrewSectionSlice → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: crew_section_slice.items[].crew
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    crew: prismicT.RelationField<"crew">;
}
/**
 * Default variation for CrewSectionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CrewSectionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CrewSectionSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CrewSectionSliceSliceDefaultPrimary>, Simplify<CrewSectionSliceSliceDefaultItem>>;
/**
 * Slice variation for *CrewSectionSlice*
 *
 */
type CrewSectionSliceSliceVariation = CrewSectionSliceSliceDefault;
/**
 * CrewSectionSlice Shared Slice
 *
 * - **API ID**: `crew_section_slice`
 * - **Description**: `CrewSectionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CrewSectionSliceSlice = prismicT.SharedSlice<"crew_section_slice", CrewSectionSliceSliceVariation>;
/**
 * Primary content in ImageGallery → Primary
 *
 */
interface ImageGallerySliceDefaultPrimary {
    /**
     * Description field in *ImageGallery → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_gallery.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in ImageGallery → Items
 *
 */
export interface ImageGallerySliceDefaultItem {
    /**
     * image field in *ImageGallery → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_gallery.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageGallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageGallerySliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageGallerySliceDefaultPrimary>, Simplify<ImageGallerySliceDefaultItem>>;
/**
 * Slice variation for *ImageGallery*
 *
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;
/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: `ImageGallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageGallerySlice = prismicT.SharedSlice<"image_gallery", ImageGallerySliceVariation>;
/**
 * Primary content in ImagesSlice → Primary
 *
 */
interface ImagesSliceDefaultPrimary {
    /**
     * Description field in *ImagesSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: images.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in ImagesSlice → Items
 *
 */
export interface ImagesSliceDefaultItem {
    /**
     * image field in *ImagesSlice → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: images.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for ImagesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Images`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImagesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImagesSliceDefaultPrimary>, Simplify<ImagesSliceDefaultItem>>;
/**
 * Slice variation for *ImagesSlice*
 *
 */
type ImagesSliceVariation = ImagesSliceDefault;
/**
 * ImagesSlice Shared Slice
 *
 * - **API ID**: `images`
 * - **Description**: `Images`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImagesSlice = prismicT.SharedSlice<"images", ImagesSliceVariation>;
/**
 * Primary content in PageHeadSectionSlice → Primary
 *
 */
interface PageHeadSectionSliceDefaultPrimary {
    /**
     * title field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * subtitle field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * image field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * border box field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: page_head_section.primary.border_box
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    border_box: prismicT.BooleanField;
    /**
     * svg title field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.primary.svg_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    svg_title: prismicT.ImageField<never>;
    /**
     * arrow connector field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: page_head_section.primary.arrow_connector
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    arrow_connector: prismicT.BooleanField;
}
/**
 * Item in PageHeadSectionSlice → Items
 *
 */
export interface PageHeadSectionSliceDefaultItem {
    /**
     * text field in *PageHeadSectionSlice → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Default variation for PageHeadSectionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PageHeadSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageHeadSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PageHeadSectionSliceDefaultPrimary>, Simplify<PageHeadSectionSliceDefaultItem>>;
/**
 * Primary content in PageHeadSectionSlice → Primary
 *
 */
interface PageHeadSectionSliceProjectPageHeadPrimary {
    /**
     * title field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * subtitle field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * image field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * border box field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: page_head_section.primary.border_box
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    border_box: prismicT.BooleanField;
    /**
     * svg title field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.primary.svg_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    svg_title: prismicT.ImageField<never>;
    /**
     * arrow connector field in *PageHeadSectionSlice → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: page_head_section.primary.arrow_connector
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    arrow_connector: prismicT.BooleanField;
}
/**
 * Item in PageHeadSectionSlice → Items
 *
 */
export interface PageHeadSectionSliceProjectPageHeadItem {
    /**
     * text field in *PageHeadSectionSlice → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page_head_section.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Project Page Head variation for PageHeadSectionSlice Slice
 *
 * - **API ID**: `projectPageHead`
 * - **Description**: `PageHeadSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageHeadSectionSliceProjectPageHead = prismicT.SharedSliceVariation<"projectPageHead", Simplify<PageHeadSectionSliceProjectPageHeadPrimary>, Simplify<PageHeadSectionSliceProjectPageHeadItem>>;
/**
 * Slice variation for *PageHeadSectionSlice*
 *
 */
type PageHeadSectionSliceVariation = PageHeadSectionSliceDefault | PageHeadSectionSliceProjectPageHead;
/**
 * PageHeadSectionSlice Shared Slice
 *
 * - **API ID**: `page_head_section`
 * - **Description**: `PageHeadSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageHeadSectionSlice = prismicT.SharedSlice<"page_head_section", PageHeadSectionSliceVariation>;
/**
 * Primary content in ProjectListSlice → Primary
 *
 */
interface ProjectListSliceSliceDefaultPrimary {
    /**
     * svg title field in *ProjectListSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project_list_slice.primary.svg_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    svg_title: prismicT.ImageField<never>;
}
/**
 * Item in ProjectListSlice → Items
 *
 */
export interface ProjectListSliceSliceDefaultItem {
    /**
     * project field in *ProjectListSlice → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: project_list_slice.items[].project
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    project: prismicT.RelationField<"project">;
}
/**
 * Default variation for ProjectListSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectListSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectListSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectListSliceSliceDefaultPrimary>, Simplify<ProjectListSliceSliceDefaultItem>>;
/**
 * Slice variation for *ProjectListSlice*
 *
 */
type ProjectListSliceSliceVariation = ProjectListSliceSliceDefault;
/**
 * ProjectListSlice Shared Slice
 *
 * - **API ID**: `project_list_slice`
 * - **Description**: `ProjectListSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectListSliceSlice = prismicT.SharedSlice<"project_list_slice", ProjectListSliceSliceVariation>;
/**
 * Primary content in Sounds → Primary
 *
 */
interface SoundsSliceDefaultPrimary {
    /**
     * description field in *Sounds → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sounds.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Sounds → Items
 *
 */
export interface SoundsSliceDefaultItem {
    /**
     * sound field in *Sounds → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: sounds.items[].sound
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    sound: prismicT.RelationField<"sound">;
    /**
     * description of sound field in *Sounds → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sounds.items[].description_of_sound
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description_of_sound: prismicT.RichTextField;
}
/**
 * Default variation for Sounds Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Sounds`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SoundsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SoundsSliceDefaultPrimary>, Simplify<SoundsSliceDefaultItem>>;
/**
 * Slice variation for *Sounds*
 *
 */
type SoundsSliceVariation = SoundsSliceDefault;
/**
 * Sounds Shared Slice
 *
 * - **API ID**: `sounds`
 * - **Description**: `Sounds`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SoundsSlice = prismicT.SharedSlice<"sounds", SoundsSliceVariation>;
/**
 * Primary content in TextAndBoxesSlice → Primary
 *
 */
interface TextAndBoxesSliceDefaultPrimary {
    /**
     * heading field in *TextAndBoxesSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_and_boxes.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heading: prismicT.KeyTextField;
    /**
     * text field in *TextAndBoxesSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: intro text
     * - **API ID Path**: text_and_boxes.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Item in TextAndBoxesSlice → Items
 *
 */
export interface TextAndBoxesSliceDefaultItem {
    /**
     * boxed text field in *TextAndBoxesSlice → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_and_boxes.items[].boxed_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    boxed_text: prismicT.RichTextField;
}
/**
 * Default variation for TextAndBoxesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextAndBoxes`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextAndBoxesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextAndBoxesSliceDefaultPrimary>, Simplify<TextAndBoxesSliceDefaultItem>>;
/**
 * Slice variation for *TextAndBoxesSlice*
 *
 */
type TextAndBoxesSliceVariation = TextAndBoxesSliceDefault;
/**
 * TextAndBoxesSlice Shared Slice
 *
 * - **API ID**: `text_and_boxes`
 * - **Description**: `TextAndBoxes`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextAndBoxesSlice = prismicT.SharedSlice<"text_and_boxes", TextAndBoxesSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CrewDocumentData, CrewDocument, FooterDocumentData, FooterDocumentDataLinksItem, FooterDocument, GlobalSettingsDocumentData, GlobalSettingsDocumentDataMainMenuItem, GlobalSettingsDocumentDataSocialMediaItem, GlobalSettingsDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, MenuDocumentData, MenuDocumentDataItemsItem, MenuDocumentDataSlicesSlice, MenuDocument, NewMenuDocumentData, NewMenuDocumentDataSubmenuItem, NewMenuDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, ProjectDocumentData, ProjectDocumentDataSlicesSlice, ProjectDocument, SoundDocumentData, SoundDocument, AllDocumentTypes, CrewSectionSliceSliceDefaultPrimary, CrewSectionSliceSliceDefaultItem, CrewSectionSliceSliceDefault, CrewSectionSliceSliceVariation, CrewSectionSliceSlice, ImageGallerySliceDefaultPrimary, ImageGallerySliceDefaultItem, ImageGallerySliceDefault, ImageGallerySliceVariation, ImageGallerySlice, ImagesSliceDefaultPrimary, ImagesSliceDefaultItem, ImagesSliceDefault, ImagesSliceVariation, ImagesSlice, PageHeadSectionSliceDefaultPrimary, PageHeadSectionSliceDefaultItem, PageHeadSectionSliceDefault, PageHeadSectionSliceProjectPageHeadPrimary, PageHeadSectionSliceProjectPageHeadItem, PageHeadSectionSliceProjectPageHead, PageHeadSectionSliceVariation, PageHeadSectionSlice, ProjectListSliceSliceDefaultPrimary, ProjectListSliceSliceDefaultItem, ProjectListSliceSliceDefault, ProjectListSliceSliceVariation, ProjectListSliceSlice, SoundsSliceDefaultPrimary, SoundsSliceDefaultItem, SoundsSliceDefault, SoundsSliceVariation, SoundsSlice, TextAndBoxesSliceDefaultPrimary, TextAndBoxesSliceDefaultItem, TextAndBoxesSliceDefault, TextAndBoxesSliceVariation, TextAndBoxesSlice };
    }
}
