// This file is generated by Slice Machine. Update with care!

import CrewSectionSlice from './CrewSectionSlice';
import ImagesSlice from './ImagesSlice';
import PageHeadSectionSlice from './PageHeadSectionSlice';
import Sounds from './Sounds';

export {
	CrewSectionSlice,
	ImagesSlice,
	PageHeadSectionSlice,
	Sounds,
};

export const components = {
	crew_section_slice: CrewSectionSlice,
	images: ImagesSlice,
	page_head_section: PageHeadSectionSlice,
	sounds: Sounds,
};
