// This file is generated by Slice Machine. Update with care!

import CrewSectionSlice from './CrewSectionSlice'
import PageHeadSectionSlice from './PageHeadSectionSlice'
import Sounds from './Sounds'

export { CrewSectionSlice, PageHeadSectionSlice, Sounds }

export const components = {
  crew_section_slice: CrewSectionSlice,
  page_head_section: PageHeadSectionSlice,
  sounds: Sounds,
}
