// This file is generated by Slice Machine. Update with care!

import PageHeadSectionSlice from './PageHeadSectionSlice'
import Sounds from './SoundsSlice'

export { PageHeadSectionSlice, Sounds }

export const components = {
  page_head_section: PageHeadSectionSlice,
  sounds: Sounds,
}
